### ISSUE TITLE
Harmonize internal backends and how to expose services to the public

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#115]
We reached a point in the way we expose web applications where it creates a set of issues that needs to be addressed.

Most web applications are configured in a way that it has to run both web server and backend code from the same virtual machine, preventing us to scale our capacity.

Also...
- Forces us to require a public IP address per web app and server, making it impossible to scale
- Makes a big configuration file, where we could simplify things by splitting per responsibility
- Has made the configuration to grow into a "hard to maintain" state, without clear conventions
- Has service resiliency and design flaws that prevents us to serve web apps well when we can’t use Fastly

**Context** Before this project, it was impossible to implement "horizontal scaling" by adding _frontend_ and/or _internal upstream_ nodes.
## Requirements
- 3 (or more) public IP addresses for public front ends web servers
- Abstract backend technology server handling (e.g. Docker container, php-fpm, HHVM, Python, Node JS, etc)
- Each _internal upstream_ exposes HTTP server on private network
- Ensure minimal changes are made on web application code (e.g. handle rewrites in _internal upstream_ service, prevent change of `Host: ...` header by using `IP:PORT`, let _frontend_ service handle header cleanup to improve caching, etc)
- Public front end proxy requests to an _internal upstream_ service, optionally filtering responses to improve cache hit rate
## Limitations
- Some services cannot be served by Fastly
  - Accounts service; We want our network to be the only ones involved in the network traffic it generates
  - Annotation service;  Because it uses WebSockets and Fastly doesn’t support it
## Proposed conventions

An _One-to-one_ convention. Each **public** name (e.g. _notes.webplatform.org_), we proxy it to **internal upstream** service on the private network, exposing an HTTP server on a pre-determined port specific for each web application. 

With this, we’ll be able to limit the number of public IP addresses while still allow us to scale by adding   _internal upstream_ node without being impacted by the number of web apps we are running.
### upstream
1. Run backend runtime service (e.g. Hypothesis’ _gunicorn_, _php5-fpm_ fastcgi, etc) and listen on unix socket or loopback (e.g. 127.0.0.1)
   1. Monit to ensure backend runtime is up and alive
2. Minimal NGINX virtual host (called "_upstream_") listening on private network serving ~~on port 80~~ a port defined per web application.
   1. Monit to ensure NGINX is up and alive
   2. Expose to private network service status information of both NGINX and Runtime (when applicable)
   3. Handle aliases, requests rewrites, and optionally other optimizations
   4. Serve static assets so that the **public** frontend can proxy it without needing to install the web app only to serve static assets
3. Internal DNS to list upstream
   1. Salt to update internal DNS to CRUD A records so the DNS always knows which private IPs ~~can handle a given web application backend~~ but use it as a query mechanism to generate config file? Or not use it. TBD
   2. ~~Assign internal name per backend (e.g. **notes.backend.production.wpdn**)~~
### public
1. Listen to public IP address, proxy requests to **internal upstream** web server.  e.g. `notes.webplatform.org` to proxy to ~~`notes.backend.production.wpdn`~~ **internal upstream** nodes that serves on port `8005` that’s assigned to our Hypothesis instance.
2. Redirect non SSL requests to its equivalent through SSL
3. Abstracts upstream server load balancing by calling internal DNS name which gives out the list of available servers, see [NGINX upstream feature](http://nginx.org/en/docs/http/ngx_http_upstream_module.html)
4. Handle response filtering  prior to serve
5. In case a _internal upstream_ server is broken, serve a human-friendly error page
#### Nice to have
1. Have web apps that are limited to run under apache and _mpm-prefork_ (i.e. MediaWiki) to be proxied the same way as any other backends
2. Handle asset caching (e.g. keep a local copy from backend response without need to install any web application to be installed locally only for static assets) 
3. Gradually switch all Apache2 configuration
4. In case of static site, strip cookies, Pragma, etc
   
   ```
   // requires HttpHeadersMore that’s part of nginx-extras
   // ref: http://wiki.nginx.org/NginxHttpHeadersMoreModule#more_clear_headers
   expires    2m;
   add_header Cache-Control public;
   more_clear_headers Set-Cookie Cache-Control Pragma;
   ```

---
## Life of an HTTP request

This illustrates where an HTTP request goes and passes through in order to serve a response to the client.

![nginx frontend](https://cloud.githubusercontent.com/assets/296940/6311315/f441f0ba-b92e-11e4-82fb-b8ed52424724.png)

While Fastly encapsulates caching and load balancing, if an application needs to be served directly by us, we cannot scale unless we rework the configuration accordingly.

---
## VirtualHosts

Each endpoints will have both an internal and a public virtual host configuration.
### Priorities
- [x] accounts.webplatform.org (served ~~directly~~, by _frontends.webplatform.org_)
- [x] api.accounts.webplatform.org (served ~~directly~~, by _frontends.webplatform.org_)
- [x] oauth.accounts.webplatform.org (served ~~directly~~, by _frontends.webplatform.org_)
- [x] profile.accounts.webplatform.org (served ~~directly~~, by _frontends.webplatform.org_)
- [x] stats.webplatform.org (served ~~directly~~, by _frontends.webplatform.org_)
  - [x] Fastly uses same IP addresses
  - [x] DNS has CNAME entry to Fastly
- [x] notes.webplatform.org (served ~~directly~~, by _frontends.webplatform.org_)
- [x] discuss.webplatform.org (served ~~directly~~, by _frontends.webplatform.org_)
  - [x] Fastly uses same IP addresses
  - [x] DNS has CNAME entry to Fastly
- [x] specs.webplatform.org
  - [x] Fastly uses same IP addresses
  - [x] DNS has CNAME entry to Fastly
  - [ ] Switch Fastly to use new production (!!!)
## Ref
- http://tomayko.com/writings/things-caches-do
- http://kly.no/posts/2010_01_26__Varnish_best_practices__.html
- https://www.mnot.net/cache_docs/
- https://moz.com/devblog/how-to-cache-http-range-requests/

**Comment by renoirb** [comment]
Don’t forget to update notes in https://docs.webplatform.org/wiki/WPD:Infrastructure/architecture/Things_to_consider_when_we_expose_service_via_Fastly_and_Varnish

**Comment by renoirb** [comment]
Ensure tracking.webplatform.org redirects to https://stats.webplatform.org/ (testthewebforward.org uses it)

**Comment by renoirb** [comment]
Refactor progress:
- **piwik** (backend key: _stats_):
  - [x] local
  - [x] public
- **notes**:
  - [x] local
  - [x] public
- **specs**:
  - [x] local
  - [x] public
- **publican**:
  - [x] local
  - [x] public
- **monitor** (backend key: _status_):
  - [x] local
  - [x] public
- **accounts**:
  - [x] local
  - [x] public
- **discuss**:
  - [x] local
  - [x] public

**Comment by renoirb** [comment]
## Proposed architecture

Each upstream service (i.e. the basic web server from a web application as a common denominator) has a set of **nodes** and is assigned a **port** number.  A web application can run from a VM (like it originally was) but would now support if another VM runs a ~~Docker container~~ (anything that exposes an HTTP service).

Having a port ensures that we can separate which service run on an internal IP address, without relying on the `Host: ...` nor change an HTTP header, but it also separate the need to use a DNS server too. By doing so, it solve possible outages due to a reboot, or outdated information, and also speed up time to render the request by eliminating a DNS query.  

A simple map stating which IP answers for the desired web application is then used to generate the configuration of the public frontend servers.

``` yml
# Upstream pillar
upstream:
  notes:
    port: 8005
    nodes:
      - 10.10.10.157
# ...
```

A web application then has two virtual hosts, one for the internal network ("`upstream`"), one for the public ("`frontend`") server.

### Frontend virtual host

```
# Generated automatically from the Upstream pillar
upstream upstream_hypothesis {
    server    10.10.10.157:8005;
    server    10.10.10.151:8005;
    server    10.10.10.17:8005;
}

server {
    listen      80;
    server_name notes.webplatform.org;
    include     common_params;
    return      301 https://notes.webplatform.org$request_uri;
}

server {
    listen      443 ssl spdy;
    server_name notes.webplatform.org;

    root    /var/www/html;
    include common_params;
    include ssl_params;

    # SSL configs...

    location / {
        proxy_pass http://upstream_hypothesis;
        include proxy_params;
        proxy_intercept_errors on;

        # WebSocket support plz
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
    }
}
```

### Upstream virtual host

```
server {
    listen  8005;

    root    /srv/webplatform/notes-server/notes_server/static;
    include common_params;

    rewrite ^/app/embed.js$ /annotator.js permanent;

    location = /annotator.js {
      rewrite    ^/annotator.js$  /embed.js last;
    }

    rewrite      ^/assets/notes-server/(.*)\? /$1;

    location / {
        proxy_pass   http://127.0.0.1:8001;
        include          proxy_params;

        # Since we are not using SSL internally, we have to force it here.
        # ref: https://docs.djangoproject.com/en/dev/ref/settings/#secure-proxy-ssl-header
        proxy_set_header X-Forwarded-Proto https;

        # Those seems to help with GUnicorn "Broken pipe" socket errors.
        # Assumption is that due to buffering because we have two NGINX servers
        # handles requests to GUnicorn; the internal (this one) and the public frontend.
        # Quoting GUnicorn docs: "If you want to be able to handle streaming request/responses or
        # other fancy features like Web sockets, you need to turn off the proxy buffering".
        # ref: http://gunicorn-docs.readthedocs.org/en/latest/deploy.html
        proxy_buffering off;

        # If we were to use a different backend hostname, we’d have to force it
        # like this.
        #proxy_set_header Host notes.webplatform.org;
    }
}
```

**Comment by renoirb** [comment]
Currently working on making names consistent. In states so far the concepts changed name many times from local, backend and upstream, but so the reference to a site (e.g. notes.webplatform.org) and the web application software running it (e.g. hypothesis). Sometimes a virtual host would run more than one web application. Creating confusion in the naming. This has to be handled too.

**Comment by WebPlatformDocs** [comment]
Everything went well, ready to merge.

**Comment by renoirb** [comment]
Note to self.

Forget about using internal name (i.e. _notes.webplatform.org_ to be refered to as _notes.backend.production.wpdn_) let’s save in communication round trips and configure NGINX to know exactly which IP addresses can serve a web app. The NGINX upstream configuration will be generated as required by Salt stack.

**Comment by renoirb** [comment]
Sent in "Work status update" email [on _devrel_ list](https://www.w3.org/mid/554BB158.6090803@w3.org)
