### ISSUE TITLE
Get W3C systeam to setup to host private data git repository  

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#145]
Please host WebPlatform private data in W3C infrastructure.

**Comment by renoirb** [comment]
Ping @astorije @jean-gui @tripu

**Comment by renoirb** [comment]
Ping @tguild

**Comment by renoirb** [comment]
Systeam don’t answer, let’s use my own judgment and stop delay.

**Comment by renoirb** [comment]
Changed scope, let’s get git repo hosting only.

**Comment by renoirb** [comment]
Required for webplatform/ops#48

**Comment by renoirb** [comment]
Sent [request reminder on Apr 22](https://www.w3.org/mid/5537BDC7.7000201@w3.org). Awaiting for a reply.

**Comment by tripu** [comment]
I am sorry that I overlooked this, @renoirb. I'm asking other systeamers about this now&hellip;

**Comment by renoirb** [comment]
I got the repository account setup @tripu. Thank you so much for the follow up!
