### ISSUE TITLE
Redeploy docs ("MediaWiki") in new production environment

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#87]

**Comment by renoirb** [comment]
Blocked by webplatform/ops#103

**Comment by shepazu** [comment]
Pending review of staging server by community.

https://lists.w3.org/Archives/Public/public-webplatform/2015Feb/0003.html

**Comment by renoirb** [comment]
Done!! Status thread is at http://status.webplatform.org/post/114007747715
