### ISSUE TITLE
Redeploy annotation-server in new production (and staging) environment

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#92]
related webplatform/ops#109

**Comment by shepazu** [comment]
Pending review of staging server by community.

https://lists.w3.org/Archives/Public/public-webplatform/2015Feb/0003.html

**Comment by renoirb** [comment]
Running in staging https://notes.webplatformstaging.org/ along with separate accounts system at https://accounts.webplatformstaging.org/
